version: '3.8'

services:
  app:
    build: 
      context: ./back/product/product
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - products-data:/app
    

  angular-frontend:
    build: 
      context: ./front/
      dockerfile: dockerfile
    ports:
      - "4200:80" 
    depends_on:
      - app

volumes:
  products-data:
    driver: local