FROM node:latest as build-step

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build --prod

FROM nginx:alpine

COPY --from=build-step /app/dist/ /usr/share/nginx/html

COPY default.conf /etc/nginx/conf.d/default.conf
